#!/usr/bin/env bash
# installs nginx and configures it on a remote server

# Update the package list and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Start nginx and listen on port 80
/usr/sbin/nginx -c /etc/nginx/nginx.conf

# Create a custom index.html file with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html

# Restart nginx
service nginx restart
