#!/usr/bin/env bash
# installs nginx and configures it on a remote server

# Update package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Set up default page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
service nginx restart
