#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.

# Install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAproxy
sudo sed -i 's/.*frontend.*$/frontend http-in\n bind *:80\n default_backend servers/g' /etc/haproxy/haproxy.cfg
sudo sed -i 's/.*backend.*$/backend servers\n balance roundrobin\n server 149607-web-01 52.90.23.6:80 check\n server 149607-web-02 52.207.96.101:80 check/g' /etc/haproxy/haproxy.cfg

# Enable HAproxy as a service
sudo service haproxy enable
sudo service haproxy restart
