#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get update 
sudo apt-get -y install haproxy

# Configure haproxy
cat << EOF |sudo tee -a /etc/haproxy/haproxy.cfg
listen load_balancer
        bind :80
	mode http
	option httpclose
	option forwardfor
        balance roundrobin
	server 149607-web-01 52.90.23.6:80 check
	server 149607-web-02 52.207.96.101:80 check
EOF

# Restart haproxy using init script
sudo /etc/init.d/haproxy restart
