#!/usr/bin/env bash

# Install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAproxy
sudo sed -i 's/.*frontend.*$/frontend http-in\n bind *:80\n default_backend servers/g' /etc/haproxy/haproxy.cfg
sudo sed -i 's/.*backend.*$/backend servers\n balance roundrobin\n server web-01 52.90.23.6:80 check\n server web-02 52.207.96.101:80 check/g' /etc/haproxy/haproxy.cfg

# Enable HAproxy as a service
sudo service haproxy enable
sudo service haproxy start
